"""
update.py

Takes in weighted network file produced by InfoPath, returns network
 with updated transmission rate distributions.

"""

from scipy import stats
import numpy as np

import csv
import matplotlib.pyplot as plt
import networkx as nx
import random
import itertools

"""
load_infopath
    Function to load network generated by InfoPath.

    @param: file name
    @ret: weighted Networkx graph
"""
def load_infopath(fname):
	# Load infopath output lines
	f = open(fname, 'rU')
	lines = [l for l in f]

	# Break lines into the node names and the edge attributes
	split = lines.index('\n')

	# Generate graph
	G = nx.DiGraph()
	node_names=[int(l.split(',')[0]) for l in lines[:split]]
	G.add_nodes_from(node_names)

	# Clean up edges
	edges_raw = [l.split(',') for l in lines[split+1:]]
	edges_clean = [((int(l[0]),int(l[1])), np.mean(map(float, l[3::2]))) for l in edges_raw]

	# Add edges to graph
	for e in edges_clean:
		G.add_edge(e[0][0],e[0][1], weight=e[1])
	for e in G.edges():
		print e, G[e[0]][e[1]]['weight']


"""
load_prior
    Function to load network with transmission priors.

    @param: file name
    @ret: weighted Networkx graph
"""
def load_prior(fname):
	# Gamma parameters
	alpha = 2
	beta = 2
	
	# Load graph
	G = nx.read_gpickle(fname)
	
	# If e was in the original graph, use its prior. Else give it a (0,0) prior.
	for e in itertools.product(G.nodes(),G.nodes()):
		if e in G.edges(): G[e[0]][e[1]]['params'] = (alpha,beta)
		else: G[e[0]][e[1]]['params'] = (0,0)
	return G

"""
update
    Updates prior network with InfoPath estimates.

    @param: infopath file name, prior file name
    @ret: weighted Networkx graph
"""
def update(infoname, priorname):
	# Load graphs
	U = load_infopath(infoname)
	P = load_prior(priorname)
	
	# If InfoPath has an estimate for an edge, update it
	for e in P.edges():
		p = P[e[0]][e[1]]['params']
		if e in U.edges():
			 p = (p[0]+1, p[1]+U[e[0]][e[1]]['weight'])
		if p = (0,0):
			P.remove_edge(*e)
	return P

infoname = 'network.txt'
priorname = 'prior.txt'
outname = 'updated.txt'

G = update(infoname, priorname)
for e in G.edges():
	print e, stats.gamma(*G[e[0]][e[1]]['params']).stats(moments='m')
nx.write_gpickle(G,outname)